name: appsec-lab2-workflow
    
on:
  schedule:
        - cron: "15 * * * *" #runs every 15 mins
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: XSS Check Script 
            run: |
              python ./gip200-xss.py
      - name: CSRF Check Script 
            run: |
              python ./gip200-csrf.py
      - name: SQLi Check Script 
            run: |
              python ./gip200-sqli.py
      - name: CMDi Check Script 
            run: |
              python ./gip200-cmdi.py
